### ISSUE TITLE
Wrong mimetype detected

### ISSUE THREAD

**Issue by Glog78** [cglindkamp/run-mailcap-rs#3]
On my system the mimetype for cbz files is wrongly choosen by this small tool. Would be amazing if that could be fixed.

``` bash
[04:07:58 ~]$ run-mailcap --debug "/mnt/winaustausch/calibre/comics/Wickline, Dan/Artemis IX_ Volume 1 (77)/Artemis IX_ Volume 1 - Wickline, Dan.cbz"
Determined mime type:
application/zip

Mailcap entries:
[04:08:15 ~]$ mimetype "/mnt/winaustausch/calibre/comics/Wickline, Dan/Artemis IX_ Volume 1 (77)/Artemis IX_ Volume 1 - Wickline, Dan.cbz"
/mnt/winaustausch/calibre/comics/Wickline, Dan/Artemis IX_ Volume 1 (77)/Artemis IX_ Volume 1 - Wickline, Dan.cbz: application/vnd.comicbook+zip
[04:08:25 ~]$
```

**Comment by cglindkamp** [comment]
That is a tricky one, because
1. It is actually not that wrong. CBZ ziles are just ZIP files containing comic book images.
2. The detection code is not inside run-mailcap-rs, but in the file utility/libmagic (http://www.darwinsys.com/file/)

So what can you do now? Short term, you could just try to revert the last commit and recompile. In this one I switched from reading the mime types database (/etc/mime.types, ~mime.types) to the file utility. At least for me, this works. I do not want to just revert this for all people, as I had my reasons for the switch (see the commit message).

I actually not really satisfied completely with file/libmagic either and wanted to implement a solution, where both can be used (file/libmagic primarily and mime.types as a fallback, when file just spits out application/octet-stream). But now I see, this would not work in your case. Well, I have to think about it.

**Comment by Glog78** [comment]
thanks for the hint with the commit. That at least should fix for what i currently use run-mailcap. Maybe you can just check which of both is more specific and use this one in the end.

a -> extract mimetype with file/libmagic ->  application/zip -> save everything after /
b -> extract mimetype with mimeinfo application/vnd.comicbook+zip -> save everything after / 

1.)  a) is included in b)  use b)
2.)  b) is included in a) use a)
3.)  if both are completely different rely  on file/libmagic

PS -> i think this is a bug in file/libmagic -> cause fun fact epub is a zip too ;) and is detected as epub+zip  in current git.

**Comment by cglindkamp** [comment]
Yeah, that would be an option. Of course the best would be, if the file utility were perfect. ;)

Now I just need to find time to implement it ...

**Comment by cglindkamp** [comment]
I did some tinkering and a solution using your steps 1 and 2 ist not so easy. It works flawlessly for zip/cbz. But has problems with rar/cbr. The problem is, "rar" is detected differently by libmagic and mime.types file. Currently, libmagic returns "application/x-rar" and using mime.types files results in "application/vnd.rar". So there would be an need for special code to support these cases, because of the prefix in front of "rar" ("x-" and "vnd.") and the difference between these prefixes. Therefore I think the best solution would be to first look into mime.types file, and if nothing could be found, use libmagic as a fallback for unknown extensions.

**Comment by cglindkamp** [comment]
I just pushed a change as described in my last comment. CBZ files should now be detected as `application/vnd.comicbook+zip`. And if you rename the extension to something completely unknown, it should still be detected it as `application/zip`.
