### ISSUE TITLE
mailcap and printf "%q" encoded strings maybe bug

### ISSUE THREAD

**Issue by Glog78** [cglindkamp/run-mailcap-rs#6]
Hello,

```
[~]$ ./epub.sh
/mnt/winaustausch/calibre/computing/Milton\,\ Michael/Head\ First\ Data\ Analysis_\ A\ Learner\'s\ Guide\ to\ Big\ Numbers\,\ Statistics\,\ and\ Good\ Decisions\ \(19\)/Head\ First\ Data\ Analysis_\ A\ Learner\'s\ Guid\ -\ Milton\,\ Michael.epub
Determined mime type: application/epub+zip
Detected by: mime.types file

Mailcap entries:
view: baca '%s'
edit:
compose:
print:
test:
needsterminal: true
copiousoutput: false
```

mailcap correctly detects that this is a epub but somehow it doesn't hand over the file correctly to baca.

```
baca /mnt/winaustausch/calibre/computing/Milton\,\ Michael/Head\ First\ Data\ Analysis_\ A\ Learner\'s\ Guide\ to\ Big\ Numbers\,\ Statistics\,\ and\ Good\ Decisions\ \(19\)/Head\ First\ Data\ Analysis_\ A\ Learner\'s\ Guid\ -\ Milton\,\ Michael.epub
```
^^ this works fine.

My guess there might be troubles with \'  probably ?

**Comment by cglindkamp** [comment]
Yes, most probably the ' is the issue here. I think it must be escaped, when ' are used for quoting in the mailcap file. If I go down this route, I may as well implement escaping when no quotes are in the mailcap file an "fix" #5 without quotes.

As far as I know, the original run-mailcap circumvented all these issues by symlinking the files to a clean name in /tmp/, but I find it confusing, when I open `foo.txt` and the application shows `/tmp/tmp.mvZHwEUj84.txt` as the opened file.

**Comment by cglindkamp** [comment]
Hi, I looked into this issue and the `'` should actually be no problem. They are already escaped since commit d3345180aecdc61d46c87cee304291903d6892c6. And some local test files work for me. I also tried other potentially problematic characters from your file name (`,`, `(` and `)`) and all seem to work. Can you maybe reduce the filename to a minimal version where the issue happens to make it easier to see, what is causing it?

Additionally, I assume you run the command directly from the shell. Can you confirm this, to exclude any potential problem with `needsterminal`?

**Comment by cglindkamp** [comment]
One further thing to try. You can add `--norun` as a parameter to see the command that run-mailcap is trying to run. You then may be able to see the problem already.

**Comment by Glog78** [comment]
```
[~]$ epub
/mnt/winaustausch/calibre/computing/Stellman\,\ Andrew/Head\ First\ PMP_\ A\ Learner\'s\ Companion\ to\ Passing\ the\ Project\ Management\ Professional\ Exam\ \(137\)/Head\ First\ PMP_\ A\ Learner\'s\ Companion\ to\ P\ -\ Stellman\,\ Andrew.epub
baca '/mnt/winaustausch/calibre/computing/Stellman\,\ Andrew/Head\ First\ PMP_\ A\ Learner\'\''s\ Companion\ to\ Passing\ the\ Project\ Management\ Professional\ Exam\ \(137\)/Head\ First\ PMP_\ A\ Learner\'\''s\ Companion\ to\ P\ -\ Stellman\,\ Andrew.epub'
[~]$
[~]$
[~]$ ls /mnt/winaustausch/calibre/computing/Stellman\,\ Andrew/Head\ First\ PMP_\ A\ Learner\'s\ Companion\ to\ Passing\ the\ Project\ Management\ Professional\ Exam\ \(137\)/Head\ First\ PMP_\ A\ Learner\'s\ Companion\ to\ P\ -\ Stellman\,\ Andrew.epub
'/mnt/winaustausch/calibre/computing/Stellman, Andrew/Head First PMP_ A Learner'\''s Companion to Passing the Project Management Professional Exam (137)/Head First PMP_ A Learner'\''s Companion to P - Stellman, Andrew.epub'
[~]$
[~]$
[~]$ ls '/mnt/winaustausch/calibre/computing/Stellman\,\ Andrew/Head\ First\ PMP_\ A\ Learner\'\''s\ Companion\ to\ Passing\ the\ Project\ Management\ Professional\ Exam\ \(137\)/Head\ First\ PMP_\ A\ Learner\'\''s\ Companion\ to\ P\ -\ Stellman\,\ Andrew.epub'
ls: cannot access '/mnt/winaustausch/calibre/computing/Stellman\,\ Andrew/Head\ First\ PMP_\ A\ Learner\'\''s\ Companion\ to\ Passing\ the\ Project\ Management\ Professional\ Exam\ \(137\)/Head\ First\ PMP_\ A\ Learner\'\''s\ Companion\ to\ P\ -\ Stellman\,\ Andrew.epub': No such file or directory
[~]$
```

https://paste.rs/JYB9z << that's the little script i use to crawl thru my library. It uses printf "%q" to get an already escaped filename to avoid breakage when handing over to somewhere else.

Still trying to find out what breaks it so i can shorten it.

**Comment by cglindkamp** [comment]
I have reason to believe the issue is more in using `printf "%q"` rather than run-mailcap-rs. Testing locally I see this:
```
$ ls foo\'.txt
"foo'.txt"
$ file=`printf "%q" "foo'.txt"`
$ echo $file
foo\'.txt
$ cat $file
cat: 'foo\'\''.txt': No such file or directory
```
So `cat` doesn't get the right filename either. I would assume that if you replace the `run-mailcap-rs` call in your script directly with `baca` it would not work, too. Additionally I would think, that the `printf` would only be able to quote the full string, if there isn't any special character in the filename, that would also need escaping in when in double quotes like `$`. So I would leave out the `printf` line completely, at least to test if it is the culprit.

Btw, maybe the meaning of %q is not so clear:
"ARGUMENT is printed in a format that **can be reused as shell input**, escaping non-printable characters with the proposed POSIX $’’ syntax."

If I use it literary as input to a subshell like in the following example, it just works:
```
echo $file | { read file2; cat "$file2"; }
```
I don't know, if this is the intended use case, but either way, using it like in this example does not give you anything of value, so I still would remove the `printf` from your script.

**Comment by Glog78** [comment]
I did remove it and for the time being we should close the issue. Thank you for looking with me into this and have a great christmas season if that relates to you.

**Comment by cglindkamp** [comment]
Have a great christmas, too.
